/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "commando-parent"
include(":commando-examples")
include(":commando-core")
include(":commando-discord")
include(":commando-javacord")
include(":javacord-example")
project(":commando-javacord").projectDir = file("commando-discord/commando-javacord")
project(":javacord-example").projectDir = file("commando-examples/javacord-example")
